courses_get:
  path: /courses/{id}
  controller: CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesGetController
  methods:  [GET]
courses_put:
  path: /courses/{id}
  controller: CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesPutController
  methods:  [PUT]
courses_create:
  path: /courses
  controller: CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesCreateController
  methods:  [POST]
courses_get_all:
  path: /courses
  controller: CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesGetAllController
  methods: [GET]